#!/usr/bin/env python
import rospy
from std_msgs.msg import Float32
from geometry_msgs.msg import Twist

wheel_spacing = 0.42
wheel_radius = 0.135

def cmd_vel_cb(cmd_vel_msg):
    v_cmd = cmd_vel_msg.linear.x
    w_cmd = cmd_vel_msg.angular.z

    w_left = (2.0 * v_cmd - w_cmd * wheel_spacing) / (2.0 * wheel_radius)
    w_right = (2.0 * v_cmd + w_cmd * wheel_spacing) / (2.0 * wheel_radius)

    left_command_pub.publish(Float32(w_left))
    right_command_pub.publish(Float32(w_right))


rospy.init_node('base_controller')

left_command_pub = rospy.Publisher('left_motor/command', Float32, queue_size=1)
right_command_pub = rospy.Publisher('right_motor/command', Float32, queue_size=1)
cmd_vel_sub = rospy.Subscriber('cmd_vel', Twist, cmd_vel_cb)

rospy.spin()
