#!/usr/bin/env python
import io
import serial
from std_msgs.msg import Bool

import rospy

rospy.init_node('deadman')

enable_pub = rospy.Publisher('enable', Bool, queue_size=1)

ser = serial.Serial(
    port='/dev/serial_radio',
    baudrate=57600,
    bytesize=8,
    parity='N',
    stopbits=1,
    xonxoff=False,
    timeout=1,
    )

sio = io.TextIOWrapper(
    io.BufferedRWPair(
        ser,
        ser,
        1, # Buffer size of 1
        ),
        encoding='ascii',
        newline='\r\n',
        line_buffering=True
    )


while not rospy.is_shutdown():
    line = sio.readline()
    if line.strip() == '1':
        enable_pub.publish(Bool(True))
    else:
        enable_pub.publish(Bool(False))

